#####################################
##          全サーバ共通           ##
#####################################
- name: apply configuration to all nodes
  hosts: all
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - common
    - tools
    - useradd

#####################################
##           STG-WEB共通           ##
#####################################
- name: apply stg_web configuration to stg_web nodes
  hosts: stg_web
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - httpd
    - php
    - mysql-client57
    - vsftpd

#####################################
##           PRD-WEB共通           ##
#####################################
- name: apply prd_web configuration to prd_web nodes
  hosts: prd_web
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - httpd
    - php
    - mysql-client57
    - vsftpd


#####################################
##            STG_DB共通           ##
#####################################
- name: apply stg_db configuration to stg_db nodes
  hosts: stg_db
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - db_backup
    - mysql-server57


#####################################
##          PRD_DB共通             ##
#####################################
- name: apply prd_db configuration to prd_db nodes
  hosts: prd_db
#  remote_user: vagrant
  remote_user: root
  become: yes
  roles:
    - db_backup
    - mysql-server57
