---
# tasks file for mysql-server57
- name: repo_add
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: mysql-install
  yum:
    name:
      - mysql-server
      - expect
    state: present
  register: result

- name: put_conf
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    backup: yes

- name: mysql_restart
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: confirm check_file
  stat: path=/usr/local/etc/mysql_stat.txt
  register: result_mysql_exit

#- name: exec_mysql_secure_installation
#  script: ../files/mysql_secure_installation
#  when: not result_mysql_exit.stat.exists

- name: put mysql_secure_installation_script
  template:
    src: ../templates/mysql_secure_installation_script
    dest: /tmp/mysql_secure_installation_script
    owner: root
    group: root
    mode: 0755

- name: exec mysql_secure_installation_script
  shell: "/tmp/mysql_secure_installation_script"
  when: not result_mysql_exit.stat.exists

- name: create check_file
  file:
    path: /usr/local/etc/mysql_stat.txt
    state: touch
    mode: "u=rw,g=r,o=r"
