---
# tasks file for mysql-server80
- name: repo_add
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: check my.cnf
  stat:
    path: /etc/my.ansible_check
  register: my_check

- name: mysql-install
  yum:
    name:
      - mysql-server
      - expect
    state: present
  notify: mysqld_start

- name: put_conf
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: restart_mysql
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

#- name: exec_mysql_secure_installation
#  script: ../files/mysql_secure_installation
#  when: not my_check.stat.exists

- name: confirm check_file
  stat: path=/usr/local/etc/mysql_stat.txt
  register: result_mysql_exit

- name: put mysql_secure_installation_script
  template:
    src: ../templates/mysql_secure_installation_script
    dest: /tmp/mysql_secure_installation_script
    owner: root
    group: root
    mode: 0755

- name: exec mysql_secure_installation_script
  shell: "/tmp/mysql_secure_installation_script"
  when: not result_mysql_exit.stat.exists

- name: create check_file
  file:
    path: /usr/local/etc/mysql_stat.txt
    state: touch
    mode: "u=rw,g=r,o=r"
