---
# tasks file for mysql-client
- name: repo_add
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present

- name: mysql-install
  yum:
    name: mysql-community-client
    state: present
